name: Ping

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Install Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.17.1

      - name: Run script
        run: node scripts/ping.js
